MALIIT_PLUGINS = maliit-$${MALIIT_INTERFACE_VERSION}/plugins
MALIIT_SERVER = maliit-server
MALIIT_PLUGINS_LIB = maliit-plugins-$${MALIIT_INTERFACE_VERSION}
MALIIT_LIB = maliit-$${MALIIT_INTERFACE_VERSION}
MALIIT_PLUGINS_HEADER = maliit-$${MALIIT_INTERFACE_VERSION}/plugins
MALIIT_HEADER = maliit-$${MALIIT_INTERFACE_VERSION}/maliit
