#!/bin/sh

export DISPLAY=:0
export PATH=/usr/bin:/usr/sbin:/bin:$PATH

if [ -z $DBUS_SESSION_BUS_ADDRESS ];then
    echo "DBUS SESSION IS NOT RUNNING"
fi

/usr/sbin/dsmetool -c 3 -T 180 -U user -t "/usr/bin/dui-im-uiserver -remote-theme"
